service: converter-csv-ndjson

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, env:SLS_AWS_STAGE, 'dev'}
  region: ${opt:region, env:SLS_AWS_REGION, 'eu-west-1'}
  deploymentBucket:
    name: converter-deployment
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:Get*"
        - "s3:PutObject"
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:s3:::"
            - converter-csv-ndjson
            - "/*"

functions:
  onFileForConversionCreated:
    handler: src/events/onFileForConversionCreated.handler
    name: onFileForConversionCreated
    timeout: 300
    events:
      - sns:
          arn:
            Fn::Join:
              - ""
              - - "arn:aws:sns:"
                - Ref: "AWS::Region"
                - ":"
                - Ref: "AWS::AccountId"
                - ":file-for-conversion-created"
          topicName: file-for-conversion-created

resources:
  Resources:
    ConverterBucket:
      Type: AWS::S3::Bucket
      DependsOn: FilesEventsTopicPolicy
      Properties:
        BucketName: converter-csv-ndjson
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders:
                - "Authorization"
              AllowedMethods:
                - GET
              AllowedOrigins:
                - "*"
            - AllowedHeaders:
                - "*"
              AllowedMethods:
                - PUT
              AllowedOrigins:
                - "*"
        NotificationConfiguration:
          TopicConfigurations:
            - Event: s3:ObjectCreated:*
              Topic:
                Ref: FileForConversionCreatedTopic

    ConverterBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: ConverterBucket
        PolicyDocument:
          Statement:
            - Effect: Allow
              Principal: "*"
              Action: s3:GetObject
              Resource:
                Fn::Join:
                  - ""
                  - - "arn:aws:s3:::"
                    - converter-csv-ndjson
                    - "/*"

    FileForConversionCreatedTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: file-for-conversion-created

    FilesEventsTopicPolicy:
      Type: AWS::SNS::TopicPolicy
      Properties:
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal: "*"
              Action: sns:Publish
              Resource: "*"
              Condition:
                ArnLike:
                  aws:SourceArn:
                    Fn::Join:
                      - ""
                      - - "arn:aws:s3:::"
                        - converter-csv-ndjson
        Topics:
          - Ref: FileForConversionCreatedTopic
